#8 - Do not send BAM configuration unless the poller is link to 1 BA …
centreon/centreon-poller-display pull request #9
Opened 2017-06-08 15:13 UTC by Moujimouja

Fix poller display when BAM is not installed on the poller display but installed on the Central

2017-07-11 15:20 UTC, kduret requested changes
Bad coding style. You need to respect PSR-2

2017-07-11 15:20 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
> +      $queryIsPollerUsedWithBAM = "SELECT count(*) as nbBa FROM mod_bam_poller_relations where poller_id = ".$poller_id;
space around dot

2017-07-11 15:20 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
> +        $isBamPoller = true;
4 spaces indentation

2017-07-11 15:20 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
> +      if($isBamPoller){
spaces around parenthesis

2017-07-11 15:20 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
>          $sql .= $this->setForeignKey(1). "\n\n";
4 lines indentation

2017-08-03 15:50 UTC, Moujimouja commented
Is it better ?

2017-08-11 11:50 UTC, kduret requested changes

2017-08-11 11:50 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
> +* Copyright 2005-2017 Centreon
you have to indent of 1 space

2017-08-11 11:50 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
> +* User: kduret
you have to indent of 1 space

2017-08-11 11:50 UTC, kduret commented on www/modules/centreon-poller-display-central/core/class/configGenerate/Bam.php
> +    *
you have to indent of 1 space

2017-08-16 07:37 UTC, merged